#端口号配置
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.78.146.114:3306/sensors?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: sensors
    password: raspberryproject
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    # 163
    host: smtp.163.com
    port:
    username: htiv124172@163.com
    password: MGYPRMHOMCRLMALC
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false